---
- name: "Create User  and configure sudo block - {{ item.username }}"
  block:
    - name: "Create User {{ item.username }}, if is a Super User."
      ansible.builtin.user:
        name: "{{ item.username }}"
        password: "{{ item.password }}"
        create_home: true
        groups: "users,mail,{{ su_sudo_group }}"
        shell: /bin/bash
        expires: -1
      when: item.is_super_user|bool

    - name: "Create User {{ item.username }}, if is not a Super User."
      ansible.builtin.user:
        name: "{{ item.username }}"
        password: "{{ item.password }}"
        create_home: true
        groups: "users,mail"
        shell: /bin/bash
        expires: -1
      when: not item.is_super_user|bool

    - name: "Create .ssh folder for {{ item.username }}"
      ansible.builtin.file:
        path: "/home/{{ item.username }}/.ssh"
        state: directory
        mode: "0700"

    - name: Check if running from Vagrant or other method, by checking User vagrant folder
      ansible.builtin.stat: path=/home/vagrant
      register: st

    - name: "Append user Public key to Authorized_keys for {{ item.username }}"
      ansible.builtin.shell: "cat /home/vagrant/.ssh/me.pub >> /home/{{ item.username }}/.ssh/authorized_keys"
      args:
        creates: "/home/{{ item.username }}/.ssh/authorized_keys"
      when: st.stat.exists

    - name: Check if running from Terraform or other method, by checking User vagrant folder
      ansible.builtin.stat: path=/home/terraform
      register: stt

    - name: "Copy user Public key to Authorized_keys for {{ item.username }}"
      ansible.builtin.shell: "cat /home/terraform/.ssh/authorized.keys >> /home/{{ item.username }}/.ssh/authorized_keys"
      args:
        creates: "/home/{{ item.username }}/.ssh/authorized_keys"
      when: stt.stat.exists

    - name: "Set permissions for ~/.ssh/authorized_keys"
      ansible.builtin.file:
        path: "/home/{{ item.username }}/.ssh/authorized_keys"
        owner: "{{ item.username }}"
        group: "{{ item.username }}"
        mode: "0600"
      when: stt.stat.exists

    - name: Get stats of root - authorized_keys
      ansible.builtin.stat:
        path: /root/.ssh/authorized_keys
      register: stroot

    - name: "Copy user Public key to Authorized_keys for {{ item.username }}"
      ansible.builtin.shell: "cat /root/.ssh/authorized_keys >> /home/{{ item.username }}/.ssh/authorized_keys"
      args:
        creates: "/home/{{ item.username }}/.ssh/authorized_keys"
      when: not st.stat.exists and not stt.stat.exists and stroot.stat.exists

    - name: "Set permissions for ~/.ssh/authorized_keys"
      ansible.builtin.file:
        path: "/home/{{ item.username }}/.ssh/authorized_keys"
        owner: "{{ item.username }}"
        group: "{{ item.username }}"
        mode: "0600"
      when: not st.stat.exists and not stt.stat.exists and stroot.stat.exists

    - name: "Add NOPASSWD Sudo into SUDOERS for {{ item.username }}"
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        line: "{{ item.username }}        ALL=(ALL)       NOPASSWD: ALL"
        validate: /usr/sbin/visudo -cf %s
      when: item.is_super_user|bool

    - name: "Set Home directory ownership - {{ item.username }}"
      ansible.builtin.file:
        path: "/home/{{ item.username }}"
        owner: "{{ item.username }}"
        group: "{{ item.username }}"
        recurse: true

    - name: "Add sudo_rules - {{ item.username }}"
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        line: "{{ item.username }}       {{ srule }}"
        validate: /usr/sbin/visudo -cf %s      
      with_items:
        - "{{ item.sudo_rules }}"
      loop_control:
        loop_var: srule
        label: "{{ srule }}"         
