---
# tasks file for sudousers
- debug: var=ansible_os_family
- name: Load OS specific Vars file
  include_vars: "{{ item }}"
  with_first_found:
    - "os_specific_{{ ansible_os_family }}.yml"
    - "os_specific_default.yml"

- name: Include secrets.yml
  include_vars: "secrets.yml"

- name: Repeat createuser block with loop
  ansible.builtin.include_tasks: createuser.yml
  with_items:
    - "{{ su_users }}"
